/*
 * 7 Days to Die V3.2 - Storage Organizer database
 * Source of truth: https://www.7dtd.tools/items  ("All items (937)")
 *
 * Source entries reviewed ........ 937
 * Excluded (non-inventory) ....... 69  (67 "Dev:" debug/cheat items, Health Bar, Missing Item)
 * Exact duplicate source names ... 6  (extra entries collapsed into one)
 * Final included inventory items . 862  (937 - 69 - 6 = 862)
 *
 * Every included item lives in exactly one box. Item names are exact source names.
 * Boxes changed from the starting structure:
 *  + "Workstations" added (Anvil, Crucible, Cooking Pot...) instead of dumping into Misc.
 *  - "Armor Mods" removed: V3.2 has no standalone armor-mod items, only schematics
 *    (Schematics box). Armor Parts / Armor Crafting Kit live in Armor.
 * Supplement (187 items) from the same site's other pages: /mods (all mods, exact names) and /blocks
 *  (curated: electrical, traps, workstations, doors, storage, building blocks). These are NOT in /items.
 *  "Armor Mods" box is back (earlier note was wrong: Intellect Mod etc. exist). Added Vehicle Mods + Dyes boxes.
 * Notes: no "Stone Pickaxe" exists in the V3.2 source; stack/bundle items are all kept.
 */
const STORAGE_DATA = {
 "game": "7 Days to Die",
 "version": "V3.2",
 "source": {
  "site": "7dtd.tools",
  "url": "https://www.7dtd.tools/items",
  "gameVersion": "V3.2",
  "sourceItemCount": 937,
  "retrieved": "2026-10-06",
  "supplemental": [
   "https://www.7dtd.tools/mods (106 mods; 2 Dev: entries skipped)",
   "https://www.7dtd.tools/blocks (5,029 blocks; only player-placeable ones curated in)"
  ]
 },
 "validation": {
  "sourceEntriesReviewed": 937,
  "excludedEntries": 69,
  "exactDuplicateSourceEntries": 6,
  "includedInventoryItems": 1049,
  "supplementalItems": 187
 },
 "exactDuplicateSourceNames": [
  "Lumberjack Hat",
  "Pipe Machine Gun Bundle",
  "Pipe Pistol Bundle",
  "Pipe Rifle Bundle",
  "Pipe Shotgun Bundle",
  "Water Filter"
 ],
 "excluded": [
  {
   "reason": "Developer/debug/cheat item (\"Dev:\" prefix) - not a legitimate player inventory item",
   "names": [
    "Dev: Assassin Quality Armor Bundle",
    "Dev: Athletic Quality Armor Bundle",
    "Dev: Biker Quality Armor Bundle",
    "Dev: Commando Quality Armor Bundle",
    "Dev: Enforcer Quality Armor Bundle",
    "Dev: Farmer Quality Armor Bundle",
    "Dev: Lumberjack Quality Armor Bundle",
    "Dev: Miner Quality Armor Bundle",
    "Dev: Nerd Quality Armor Bundle",
    "Dev: Nomad Quality Armor Bundle",
    "Dev: Preacher Quality Armor Bundle",
    "Dev: Primitive Quality Armor Bundle",
    "Dev: Raider Quality Armor Bundle",
    "Dev: Ranger Quality Armor Bundle",
    "Dev: Rogue Quality Armor Bundle",
    "Dev: Scavenger Quality Armor Bundle",
    "Dev: Buff Abrasion 1800",
    "Dev: Buff Abrasion 2400",
    "Dev: Buff Abrasion 3200",
    "Dev: Buff Abrasion 600",
    "Dev: Buff Broken Arm",
    "Dev: Buff Broken Leg",
    "Dev: Buff Concussion",
    "Dev: Buff Dysentery",
    "Dev: Buff Fatigued",
    "Dev: Buff Infection",
    "Dev: Buff Laceration",
    "Dev: Buff Sprained Arm",
    "Dev: Buff Sprained Leg",
    "Dev: Give XP - T1",
    "Dev: Give XP - T2",
    "Dev: Give XP - T3",
    "Dev: Give XP - T4",
    "Dev: Give XP - T5",
    "Dev: Give XP - T6",
    "Dev: T1 Quest Ticket",
    "Dev: T2 Quest Ticket",
    "Dev: T3 Quest Ticket",
    "Dev: T4 Quest Ticket",
    "Dev: T5 Quest Ticket",
    "Dev: T6 Quest Ticket",
    "Dev: Admin Block Replace Tool",
    "Dev: All Crafting Skills Magazine",
    "Dev: All Mods Schematic",
    "Dev: All Perks Book",
    "Dev: Crafting Resources Pack",
    "Dev: Electricity Test Note",
    "Dev: Find Trader Quest",
    "Dev: Full Respec",
    "Dev: Full Respec with XP",
    "Dev: Hammer Of God",
    "Dev: Instant Death Pistol",
    "Dev: Level Design Tools",
    "Dev: Note to Testers",
    "Dev: Nuke Grenade",
    "Dev: Paint Brush",
    "Dev: Pimp Mining Helmet",
    "Dev: Ring of Fire",
    "Dev: Rocket Boots",
    "Dev: Stamina Boots",
    "Dev: Stamina Only Boots",
    "Dev: Super Digger",
    "Dev: Super Wrench",
    "Dev: Terrain Modeling Tool",
    "Dev: Tough Guy Shirt",
    "Dev: Upgrade Resources Pack",
    "Dev: Workstations and Tools Pack"
   ]
  },
  {
   "reason": "UI-only object (not a storable item)",
   "names": [
    "Health Bar"
   ]
  },
  {
   "reason": "Internal placeholder entry",
   "names": [
    "Missing Item"
   ]
  }
 ],
 "boxes": [
  {
   "id": "pistols",
   "name": "Pistols",
   "items": [
    ".44 Desert Vulture",
    ".44 Desert Vulture Bundle",
    ".44 Desert Vulture Legendary Bundle",
    ".44 Magnum",
    ".44 Magnum Bundle",
    "Legendary Pistol Crafting Bundle",
    "Pipe Pistol",
    "Pipe Pistol Bundle",
    "Pistol",
    "Pistol Bundle",
    "Pistol Crafting Bundle"
   ]
  },
  {
   "id": "machine-guns",
   "name": "Machine Guns",
   "items": [
    "AK-47 Bundle",
    "AK-47 Machine Gun",
    "Legendary Machine Gun Crafting Bundle",
    "M60 Machine Gun",
    "M60 Machine Gun Bundle",
    "M60 Machine Gun Legendary Bundle",
    "Machine Gun Crafting Bundle",
    "Pipe Machine Gun",
    "Pipe Machine Gun Bundle",
    "SMG-5",
    "SMG-5 Bundle",
    "SMG-5 Legendary Bundle",
    "Tactical Assault Rifle",
    "Tactical Assault Rifle Bundle"
   ]
  },
  {
   "id": "rifles",
   "name": "Rifles",
   "items": [
    "Hunting Rifle",
    "Hunting Rifle Bundle",
    "Legendary Rifle Crafting Bundle",
    "Lever Action Rifle",
    "Lever Action Rifle Bundle",
    "Pipe Rifle",
    "Pipe Rifle Bundle",
    "Rifle Crafting Bundle",
    "Sniper Rifle",
    "Sniper Rifle Bundle",
    "Sniper Rifle Legendary Bundle"
   ]
  },
  {
   "id": "shotguns",
   "name": "Shotguns",
   "items": [
    "Auto Shotgun",
    "Auto Shotgun Bundle",
    "Auto Shotgun Legendary Bundle",
    "Double Barrel Shotgun",
    "Double Barrel Shotgun Bundle",
    "Legendary Shotgun Crafting Bundle",
    "Pipe Shotgun",
    "Pipe Shotgun Bundle",
    "Pump Shotgun",
    "Pump Shotgun Bundle",
    "Shotgun Crafting Bundle"
   ]
  },
  {
   "id": "bows-crossbows",
   "name": "Bows & Crossbows",
   "items": [
    "Bow Crafting Bundle",
    "Compound Bow",
    "Compound Crossbow",
    "Iron Crossbow",
    "Legendary Bow Crafting Bundle",
    "Primitive Bow",
    "Wooden Bow"
   ]
  },
  {
   "id": "melee",
   "name": "Melee Weapons",
   "items": [
    "Baseball Bat",
    "Baton Crafting Bundle",
    "Bone Knife",
    "Candy Cane Club",
    "Candy Cane Knife",
    "Hunting Knife",
    "Iron Knuckles",
    "Iron Sledgehammer",
    "Iron Spear",
    "Knuckle Wraps",
    "Legendary Baton Crafting Bundle",
    "Legendary Machete Crafting Bundle",
    "Legendary Steel Club Crafting Bundle",
    "Legendary Steel Knuckle Crafting Bundle",
    "Legendary Steel Sledgehammer Crafting Bundle",
    "Legendary Steel Spear Crafting Bundle",
    "Machete",
    "Machete Crafting Bundle",
    "Pipe Baton",
    "Pipe Baton Bundle",
    "Steel Club",
    "Steel Club Crafting Bundle",
    "Steel Knuckle Crafting Bundle",
    "Steel Knuckles",
    "Steel Sledgehammer",
    "Steel Sledgehammer Crafting Bundle",
    "Steel Spear",
    "Steel Spear Crafting Bundle",
    "Stone Sledgehammer",
    "Stone Spear",
    "Stun Baton",
    "Wooden Club"
   ]
  },
  {
   "id": "tools",
   "name": "Tools",
   "items": [
    "Auger",
    "Candle",
    "Chainsaw",
    "Claw Hammer",
    "Flashlight",
    "Impact Driver",
    "Iron Fireaxe",
    "Iron Pickaxe",
    "Iron Shovel",
    "Legendary Motor Tools Crafting Bundle",
    "Legendary Steel Tools Crafting Bundle",
    "Lockpick",
    "Motor Tools Crafting Bundle",
    "Nailgun",
    "Paint",
    "Paint Brush",
    "Ratchet",
    "Repair Kit",
    "Sewing Kit",
    "Stack of Lockpicks (50)",
    "Steel Axe",
    "Steel Pickaxe",
    "Steel Shovel",
    "Steel Tools Crafting Bundle",
    "Stone Axe",
    "Stone Shovel",
    "Taza's Stone Axe",
    "Torch",
    "Wrench"
   ]
  },
  {
   "id": "workstations",
   "name": "Workstations",
   "items": [
    "Advanced Bellows",
    "Anvil",
    "Apiary",
    "Beaker",
    "Bucket",
    "Campfire",
    "Cement Mixer",
    "Chemistry Station",
    "Chicken Coop",
    "Cooking Grill",
    "Cooking Pot",
    "Crucible",
    "Dew Collector",
    "Forge",
    "Workbench"
   ]
  },
  {
   "id": "weapon-parts",
   "name": "Weapon Parts",
   "items": [
    "Baton Parts",
    "Bow / Crossbow Parts",
    "Handgun Parts",
    "Legendary Parts",
    "Machete Parts",
    "Machine Gun Parts",
    "Motor Tool Parts",
    "Rifle Parts",
    "Rocket Launcher Parts",
    "Shotgun Parts",
    "Steel Club Parts",
    "Steel Knuckles Parts",
    "Steel Sledgehammer Parts",
    "Steel Spear Parts",
    "Steel Tool Parts"
   ]
  },
  {
   "id": "weapon-mods",
   "name": "Weapon & Tool Mods",
   "items": [
    "Arrow Rest Mod",
    "Barbed Wire Mod",
    "Barrel Extender Mod",
    "Bipod Mod",
    "Bunker Buster Mod",
    "Burning Shaft Mod",
    "Buttkick 3000 Mod",
    "Buttkick 4000 Mod - Perks",
    "Cripple 'Em Mod",
    "Diamond Blade Tip Mod",
    "Drum Magazine Mod",
    "Ergonomic Grip Mod",
    "Fireman's Axe Mod",
    "Fore Grip Mod",
    "Fortifying Grip Mod",
    "Grave Digger Mod",
    "Iron Breaker Mod",
    "Laser Sight Mod",
    "Magazine Extender Mod",
    "Melee Mods Bundle 01",
    "Melee Mods Bundle 02",
    "Melee Mods Bundle 03",
    "Metal Chain Mod",
    "Metal Spikes Mod",
    "Motor Tool Large Tank Mod",
    "Motor Tool Small Tank Mod",
    "Muzzle Brake Mod",
    "Polymer String Mod",
    "Rad Remover Mod",
    "Ranged Mods Bundle 01",
    "Ranged Mods Bundle 02",
    "Ranged Mods Bundle 03",
    "Reflex Sight Mod",
    "Retracting Stock Mod",
    "Sawed-Off Shotgun Mod",
    "Scope 2x Mod",
    "Scope 4x Mod",
    "Scope 8x Mod",
    "Serrated Blade Mod",
    "Shotgun Choke Mod",
    "Shotgun Duckbill Mod",
    "Shotgun Tube Extender Mod",
    "Silencer Mod",
    "Structural Brace Mod",
    "Stun Baton Repulsor Mod",
    "Tempered Blade Mod",
    "The Decapitizer",
    "The Hunter Mod",
    "Trigger Group: Burst Mod",
    "Trigger Group: Full Auto Mod",
    "Trigger Group: Semi Mod",
    "Weapon Flashlight Mod",
    "Weighted Head Mod",
    "Wood Splitter Mod"
   ]
  },
  {
   "id": "armor-mods",
   "name": "Armor Mods",
   "items": [
    "Advanced Armor Fittings Mod",
    "Advanced Armor Plating Mod",
    "Advanced Muffled Connectors Mod",
    "Agility Mod",
    "Armor Double Pocket Mod",
    "Armor Fittings Mod",
    "Armor Plating Mod",
    "Armor Pocket Mod",
    "Armor Quad Pocket Mod",
    "Armor Triple Pocket Mod",
    "Bandolier Mod",
    "Cigar Mod",
    "Fortitude Mod",
    "Helmet Light Mod",
    "Impact Bracing Mod",
    "Intellect Mod",
    "Jump Jets Mod",
    "Muffled Connectors Mod",
    "Night Vision Mod",
    "Patchwork Insulated Armor Mod",
    "Perception Mod",
    "Radiation Ready Mod",
    "Stealth Boots Mod",
    "Strength Mod",
    "Tattered Insulated Armor Mod",
    "ThermaCore Insulated Armor Mod",
    "Treasure Hunter's Mod",
    "Water Purifier Mod"
   ]
  },
  {
   "id": "vehicle-mods",
   "name": "Vehicle Mods",
   "items": [
    "Vehicle Armor Mod",
    "Vehicle Expanded Seating Mod",
    "Vehicle Fuel Saver Mod",
    "Vehicle Mega Mod",
    "Vehicle Off Road Headlights Mod",
    "Vehicle Plow Mod",
    "Vehicle Reserve Fuel Tank Mod",
    "Vehicle Storage Mod",
    "Vehicle Super Charger Mod"
   ]
  },
  {
   "id": "dyes",
   "name": "Dyes",
   "items": [
    "Dye: Black",
    "Dye: Blue",
    "Dye: Brown",
    "Dye: Green",
    "Dye: Orange",
    "Dye: Pink",
    "Dye: Purple",
    "Dye: Red",
    "Dye: Solvent",
    "Dye: Yellow"
   ]
  },
  {
   "id": "ammo-9mm",
   "name": "9mm Ammo",
   "items": [
    "9mm Ammo",
    "AP 9mm Ammo",
    "Box of 9mm Ammo (100)",
    "Box of AP 9mm Ammo (100)",
    "Box of HP 9mm Ammo (100)",
    "HiPower 9mm Ammo"
   ]
  },
  {
   "id": "ammo-44",
   "name": ".44 Ammo",
   "items": [
    ".44 Magnum Ammo",
    "AP .44 Magnum Ammo",
    "Box of .44 Magnum Ammo (100)",
    "Box of AP .44 Magnum Ammo (100)",
    "Box of HP .44 Magnum Ammo (100)",
    "HiPower .44 Magnum Ammo"
   ]
  },
  {
   "id": "ammo-762",
   "name": "7.62 Ammo",
   "items": [
    "7.62mm Ammo",
    "AP 7.62mm Ammo",
    "Box of 7.62mm Ammo (100)",
    "Box of AP 7.62mm Ammo (100)",
    "Box of HP 7.62mm Ammo (100)",
    "HiPower 7.62mm Ammo"
   ]
  },
  {
   "id": "ammo-shotgun",
   "name": "Shotgun Ammo",
   "items": [
    "Box of Shotgun AP Slugs (100)",
    "Box of Shotgun Breaching Slugs (100)",
    "Box of Shotgun Shells (100)",
    "Shotgun AP Slug (Ammo)",
    "Shotgun Breaching Slug (Ammo)",
    "Shotgun Shell (Ammo)"
   ]
  },
  {
   "id": "ammo-arrow",
   "name": "Arrow Ammo",
   "items": [
    "Box of Exploding Arrows (75)",
    "Box of Flaming Arrows (100)",
    "Box of Iron Arrows (100)",
    "Box of Steel Arrows (100)",
    "Box of Stone Arrows (100)",
    "Exploding Arrow (Ammo)",
    "Flaming Arrow (Ammo)",
    "Iron Arrow (Ammo)",
    "Steel Arrow (Ammo)",
    "Stone Arrow (Ammo)"
   ]
  },
  {
   "id": "ammo-bolt",
   "name": "Crossbow Bolt Ammo",
   "items": [
    "Box of Exploding Crossbow Bolts (75)",
    "Box of Flaming Crossbow Bolts (100)",
    "Box of Iron Crossbow Bolts (100)",
    "Box of Steel Crossbow Bolts (100)",
    "Box of Stone Crossbow Bolts (100)",
    "Exploding Crossbow Bolts",
    "Flaming Crossbow Bolt (Ammo)",
    "Iron Crossbow Bolt (Ammo)",
    "Steel Crossbow Bolt (Ammo)",
    "Stone Crossbow Bolt (Ammo)"
   ]
  },
  {
   "id": "explosives",
   "name": "Explosives",
   "items": [
    "Contact Grenade (Ammo)",
    "Grenade (Ammo)",
    "Legendary Rocket Launcher Crafting Bundle",
    "Molotov Cocktail (Ammo)",
    "Pipe Bomb (Ammo)",
    "Rocket Frag (Ammo)",
    "Rocket HE (Ammo)",
    "Rocket Launcher",
    "Rocket Launcher Crafting Bundle",
    "Stick of Dynamite (Ammo)",
    "Timed Charge (Ammo)"
   ]
  },
  {
   "id": "ammo-robotic",
   "name": "Robotic Ammo",
   "items": [
    "AP Robotic Turret Ammo",
    "Box of AP Robotic Turret Ammo (1000)",
    "Box of Robotic Turret Ammo (1000)",
    "Box of Robotic Turret Shell Ammo (1000)",
    "Robotic Turret Ammo",
    "Robotic Turret Shells (Ammo)"
   ]
  },
  {
   "id": "armor",
   "name": "Armor",
   "items": [
    "Armor Crafting Kit",
    "Armor Parts",
    "Assassin Boots",
    "Assassin Gloves",
    "Assassin Hood",
    "Assassin Outfit",
    "Athletic Gloves",
    "Athletic Hat",
    "Athletic Outfit",
    "Athletic Shoes",
    "Big Beak Gloves",
    "Big Beak Headgear",
    "Big Beak Outfit",
    "Big Beak Shoes",
    "Biker Boots",
    "Biker Gloves",
    "Biker Helmet",
    "Biker Outfit",
    "Butcher Boots",
    "Butcher Gloves",
    "Butcher Helmet",
    "Butcher Outfit",
    "Commando Boots",
    "Commando Gloves",
    "Commando Helmet",
    "Commando Outfit",
    "Crimson Warlord Boots",
    "Crimson Warlord Gloves",
    "Crimson Warlord Helmet",
    "Crimson Warlord Outfit",
    "Desert Boots",
    "Desert Gloves",
    "Desert Hat",
    "Desert Outfit",
    "Enforcer Gloves",
    "Enforcer Outfit",
    "Enforcer Shoes",
    "Enforcer Sunglasses",
    "Farmer Boots",
    "Farmer Gloves",
    "Farmer Hat",
    "Farmer Outfit",
    "Hellreaver Boots",
    "Hellreaver Gloves",
    "Hellreaver Helmet",
    "Hellreaver Outfit",
    "Lumberjack Boots",
    "Lumberjack Gloves",
    "Lumberjack Hat",
    "Lumberjack Outfit",
    "Marauder Boots",
    "Marauder Gloves",
    "Marauder Helmet",
    "Marauder Outfit",
    "Miner Boots",
    "Miner Gloves",
    "Miner Helmet",
    "Miner Outfit",
    "Nerd Boots",
    "Nerd Gloves",
    "Nerd Goggles",
    "Nerd Outfit",
    "Nerd Tats",
    "Nomad Boots",
    "Nomad Gloves",
    "Nomad Headgear",
    "Nomad Outfit",
    "Pirate Boots",
    "Pirate Gloves",
    "Pirate Helmet",
    "Pirate Outfit",
    "Preacher Boots",
    "Preacher Gloves",
    "Preacher Hat",
    "Preacher Outfit",
    "Primitive Gloves",
    "Primitive Hood",
    "Primitive Outfit",
    "Primitive Shoes",
    "Raider Boots",
    "Raider Gloves",
    "Raider Helmet",
    "Raider Outfit",
    "Ranger Boots",
    "Ranger Gloves",
    "Ranger Hat",
    "Ranger Outfit",
    "Rogue Boots",
    "Rogue Gloves",
    "Rogue Hood",
    "Rogue Outfit",
    "Samurai Boots",
    "Samurai Gloves",
    "Samurai Helmet",
    "Samurai Outfit",
    "Scavenger Boots",
    "Scavenger Gloves",
    "Scavenger Hat",
    "Scavenger Outfit",
    "Watcher Boots",
    "Watcher Gloves",
    "Watcher Helmet",
    "Watcher Outfit",
    "Winter Boots",
    "Winter Gloves",
    "Winter Hat",
    "Winter Outfit",
    "Working Stiff Boots",
    "Working Stiff Gloves",
    "Working Stiff Helmet",
    "Working Stiff Outfit"
   ]
  },
  {
   "id": "clothing",
   "name": "Clothing & Costumes",
   "items": [
    "Beach Gloves",
    "Beach Hat",
    "Beach Sandals",
    "Beach Visor",
    "Beachwear",
    "Blue Pimp Hat",
    "Casual Boots",
    "Casual Gloves",
    "Casual Outfit",
    "Classic Survivor Boots",
    "Classic Survivor Helmet",
    "Classic Survivor Outfit",
    "Crack-A-Book Hat",
    "Crack-A-Book Outfit",
    "Elf Hat",
    "Hoarder Boots",
    "Hoarder Gloves",
    "Hoarder Helmet",
    "Hoarder Outfit",
    "Inspector Mask",
    "Mo Power Hat",
    "Mo Power Outfit",
    "Monster Mask",
    "Noble Thief Mask",
    "Pass-N-Gas Hat",
    "Pass-N-Gas Outfit",
    "Penny Pincher Mask",
    "Pop-N-Pills Hat",
    "Pop-N-Pills Outfit",
    "Purple Pimp Hat",
    "Reindeer Hat",
    "Santa Hat",
    "Savage Country Hat",
    "Savage Country Outfit",
    "Shamway Hat",
    "Shamway Outfit",
    "Shotgun Messiah Hat",
    "Shotgun Messiah Outfit",
    "Snowman Hat",
    "The Hatter Mask",
    "Tree Hat",
    "Vampire Mask",
    "Werewolf Mask",
    "Working Stiffs Hat",
    "Working Stiffs Outfit",
    "Zombie Mask"
   ]
  },
  {
   "id": "armor-layers",
   "name": "Armor Layers",
   "items": [
    "Desert Gear",
    "Patchwork Cap Liner",
    "Patchwork Glove Liners",
    "Patchwork Long Underwear",
    "Patchwork Socks",
    "Radiation Gear",
    "Smoke Gear",
    "Snow Gear",
    "Tattered Cap Liner",
    "Tattered Glove Liners",
    "Tattered Socks",
    "Tattered Undergarments",
    "ThermaCore Cap Liner",
    "ThermaCore Combat Layer",
    "ThermaCore Glove Liners",
    "ThermaCore Socks",
    "Water Filter"
   ]
  },
  {
   "id": "building",
   "name": "Building Materials",
   "items": [
    "Brick Block",
    "Bulletproof Glass Block",
    "Business Glass Block",
    "Cement",
    "Clay Soil",
    "Cobblestone Block",
    "Cobblestone Rocks",
    "Concrete Barrier",
    "Concrete Block",
    "Concrete Mix",
    "Crushed Sand",
    "Forged Iron",
    "Forged Steel",
    "Glass Block",
    "Iron Bars",
    "Nails",
    "Sandbags",
    "Small Stone",
    "Stack of Small Stone (6000)",
    "Stack of Wood (6000)",
    "Steel Block",
    "Wood",
    "Wood Block",
    "Wood Fence"
   ]
  },
  {
   "id": "doors-storage",
   "name": "Doors, Ladders & Storage Blocks",
   "items": [
    "Bedroll",
    "Hardened Chest",
    "Iron Cellar Door",
    "Iron Door",
    "Iron Double Door",
    "Iron Hatch",
    "Iron Ladder",
    "Iron Shutters",
    "Iron Storage Crate",
    "Land Claim Block",
    "Reinforced Chest",
    "Reinforced Drawbridge",
    "Steel Cellar Door",
    "Steel Door",
    "Steel Door Double",
    "Steel Hatch",
    "Steel Ladder",
    "Steel Shutters",
    "Steel Storage Crate",
    "Wood Cellar Door",
    "Wood Door",
    "Wood Double Door",
    "Wood Hatch",
    "Wood Shutters",
    "Wood Storage Crate",
    "Wooden Ladder"
   ]
  },
  {
   "id": "crafting",
   "name": "Crafting Materials",
   "items": [
    "Animal Fat",
    "Beeswax",
    "Bone",
    "Bottle of Acid",
    "Brass",
    "Cloth Fragment",
    "Coal",
    "Cotton",
    "Duct Tape",
    "Feather",
    "Glue",
    "Headlight",
    "Iron",
    "Lead",
    "Leather",
    "Lens",
    "Mechanical Parts",
    "Nitrate Powder",
    "Oil",
    "Oil Shale",
    "Paper",
    "Plant Fibers",
    "Rotting Flesh",
    "Scrap Polymers",
    "Short Iron Pipe",
    "Spring",
    "Stack of Brass (6000)",
    "Stack of Coal (6000)",
    "Stack of Iron (6000)",
    "Stack of Lead (6000)",
    "Stack of Nitrate Powder (6000)",
    "Stack of Oil Shale (6000)",
    "Tarp"
   ]
  },
  {
   "id": "ammo-components",
   "name": "Ammo Components",
   "items": [
    "Ammo Crafting Bundle",
    "Buckshot",
    "Bullet Casing",
    "Bullet Tip",
    "Gunpowder",
    "Iron Arrowhead",
    "Rocket Casing",
    "Rocket Tip",
    "Stack of Gunpowder (1000)",
    "Steel Arrowhead"
   ]
  },
  {
   "id": "salvage",
   "name": "Salvage & Valuables",
   "items": [
    "Brass Candlestick",
    "Brass Door Knob",
    "Brass Radiator",
    "Brass Trophy",
    "Broken Glass",
    "Duke's Casino Token",
    "Gold Nugget",
    "Lead Fishing Weight",
    "Lead Trophy",
    "Old Cash",
    "Raw Diamond",
    "Silver Nugget"
   ]
  },
  {
   "id": "food",
   "name": "Food",
   "items": [
    "Ash Chicken Stew",
    "Bacon and Eggs",
    "Baked Potato",
    "Blueberry Pie",
    "Boiled Egg",
    "Boiled Meat",
    "Can of Cat Food",
    "Can of Chili",
    "Can of Dog Food",
    "Can of Miso",
    "Can of Pasta",
    "Can of Pears",
    "Can of Peas",
    "Can of Salmon",
    "Can of Sham",
    "Can of Stock",
    "Can of Tuna",
    "Charred Meat",
    "Chicken Nuggets",
    "Chicken Ration",
    "Chicken Soup",
    "Chicken Wings",
    "Chili Dog",
    "Corn Bread",
    "Fish Tacos",
    "Food Bundle 01",
    "Food Bundle 02",
    "Food Bundle 03",
    "Grilled Corn",
    "Grilled Meat",
    "Gumbo Stew",
    "Hobo Stew",
    "Honey Brisket",
    "Honey Glazed Sham",
    "Lamb Rations",
    "Large Beef Ration",
    "Meat Stew",
    "Old Sham Sandwich",
    "Pumpkin Bread",
    "Pumpkin Cheesecake",
    "Pumpkin Pie",
    "Roadrunner Chicken Jerky",
    "Scorcher Stew",
    "Sham Chowder",
    "Shepherd's Pie",
    "Spaghetti",
    "Steak and Potato Meal",
    "Tuna Fish Gravy Toast",
    "Vegetable Stew"
   ]
  },
  {
   "id": "food-ingredients",
   "name": "Food Ingredients",
   "items": [
    "Coffee Beans",
    "Cornmeal",
    "Egg",
    "Jar of Honey",
    "Raw Meat",
    "Raw Meat Bundle"
   ]
  },
  {
   "id": "drinks",
   "name": "Drinks",
   "items": [
    "Beer",
    "Blackstrap Coffee",
    "Bucket of Water",
    "Coffee",
    "Empty Water Jar",
    "Goldenrod Tea",
    "Honey Tea",
    "Murky Water",
    "Pure Mineral Water",
    "Red Tea",
    "Water",
    "Yucca Juice",
    "Yucca Juice Smoothie"
   ]
  },
  {
   "id": "medical",
   "name": "Medical",
   "items": [
    "Aloe Cream",
    "Antibiotics",
    "Bandage",
    "Black Lung Serum",
    "Blood Bag",
    "First Aid Bandage",
    "First Aid Kit",
    "Herbal Antibiotics",
    "Painkillers",
    "Plaster Cast",
    "Splint",
    "Sunstroke Tonic",
    "Vitamins"
   ]
  },
  {
   "id": "boosters",
   "name": "Boosters & Buffs",
   "items": [
    "Armored Up",
    "Atom Junkies",
    "Big Hitters",
    "Covert Cats",
    "Eye Candy",
    "Fallout Flush",
    "Fort Bites",
    "Furious Fists",
    "Gatherer",
    "Get Hammered",
    "Grandpa's Awesome Sauce",
    "Grandpa's Fergit'n Elixir",
    "Grandpa's Learnin' Elixir",
    "Grandpa's Moonshine",
    "Hackers",
    "Handy Land",
    "Jail Breakers",
    "Knife Guy",
    "Mega Crush",
    "Oh Shitz Drops",
    "Recog",
    "Rock Busters",
    "Skull Crushers",
    "Smoker",
    "Steroids",
    "Sugar Butts",
    "Testosterone Extract"
   ]
  },
  {
   "id": "farming",
   "name": "Farming & Animals",
   "items": [
    "Aloe Vera Leaf",
    "Blueberries",
    "Brood Box",
    "Brooding Lamp",
    "Chicken Feed",
    "Chicken Run",
    "Chrysanthemum",
    "Domesticated Chicken",
    "Ear of Corn",
    "Ear of Super Corn",
    "Farm Bundle 01",
    "Farm Bundle 02",
    "Farm Bundle 03",
    "Farm Plot",
    "Goldenrod Flower",
    "Honey Extractor",
    "Hops Flower",
    "Mushrooms",
    "Nesting Box",
    "Potato",
    "Pumpkin",
    "Queen Bee",
    "Radiated Mushrooms",
    "Wild Chicken",
    "Yucca Fruit"
   ]
  },
  {
   "id": "electrical",
   "name": "Electrical",
   "items": [
    "Basic Light Bulb",
    "Battery Bank",
    "Battery Bank Bundle",
    "Electric Timer Relay",
    "Electric Wire Relay",
    "Electrical Parts",
    "Fluorescent Light",
    "Generator Bank",
    "Generator Bank Bundle",
    "Industrial Light",
    "Industrial Light Bulb",
    "Lantern",
    "Lead Car Battery",
    "Motion Sensor",
    "Old Lantern",
    "Security Camera Bundle",
    "Solar Bank",
    "Solar Bank Bundle",
    "Solar Cell",
    "Speaker",
    "Spotlight",
    "Switch",
    "Torch Wall Holder",
    "Trigger Plate 1x1",
    "Trigger Plate 1x5",
    "Tripwire Post",
    "Wall Torch",
    "Wire Tool"
   ]
  },
  {
   "id": "traps",
   "name": "Traps & Defense",
   "items": [
    "Air Filter Land Mine",
    "Auto Turret Bundle",
    "Barbed Wire",
    "Barbed Wire Fence",
    "Blade Trap",
    "Blade Trap Bundle",
    "Cooking Pot Mine",
    "Dart Trap",
    "Dart Trap Bundle",
    "Dynamic Grate Trap",
    "Electric Fence Post",
    "Electrical Traps",
    "Flamethrower Trap",
    "Hubcap Land Mine",
    "Iron Dart (Ammo)",
    "Iron Spikes Trap",
    "M60 Auto Turret",
    "Shotgun Auto Turret",
    "Shotgun Turret Bundle",
    "SMG Auto Turret",
    "Tin Land Mine",
    "Traps Bundle 01",
    "Traps Bundle 02",
    "Wood Spikes Trap"
   ]
  },
  {
   "id": "robotics",
   "name": "Robotics",
   "items": [
    "Legendary Robotics Crafting Bundle",
    "Robotic Drone",
    "Robotic Drone Armor Plating Mod",
    "Robotic Drone Cargo Mod",
    "Robotic Drone Medic Mod",
    "Robotic Drone Morale Booster Mod",
    "Robotic Drone Stun Mod",
    "Robotic Drone Weapon Mod",
    "Robotic Headlamp Mod",
    "Robotic Sledge",
    "Robotic Turret",
    "Robotics Crafting Bundle",
    "Robotics Parts"
   ]
  },
  {
   "id": "vehicles",
   "name": "Vehicles & Parts",
   "items": [
    "4x4 Parts Bundle",
    "4x4 Truck",
    "4x4 Truck Accessories",
    "4x4 Truck Chassis",
    "Bicycle",
    "Bicycle Chassis",
    "Bicycle Handlebars",
    "Engine",
    "Gas Can",
    "Gyrocopter",
    "Gyrocopter Accessories",
    "Gyrocopter Chassis",
    "Gyrocopter Parts Bundle",
    "Minibike",
    "Minibike Chassis",
    "Minibike Handlebars",
    "Minibike Parts Bundle",
    "Motorcycle",
    "Motorcycle Chassis",
    "Motorcycle Handlebars",
    "Motorcycle Parts Bundle",
    "Stack of Gas Cans (5000)",
    "Vehicle Parts Bundle",
    "Wheel"
   ]
  },
  {
   "id": "books",
   "name": "Books & Magazines",
   "items": [
    "3 Book Bundle",
    "4 Book Bundle",
    "5 Book Bundle",
    "6 Book Bundle",
    "7 Book Bundle",
    "Art of Mining Vol 1",
    "Art of Mining Vol 2",
    "Art of Mining Vol 3",
    "Art of Mining Vol 4",
    "Art of Mining Vol 5",
    "Art of Mining Vol 6",
    "Art of Mining Vol 7",
    "Automatic Weapons Handbook Vol 1",
    "Automatic Weapons Handbook Vol 2",
    "Automatic Weapons Handbook Vol 3",
    "Automatic Weapons Handbook Vol 4",
    "Automatic Weapons Handbook Vol 5",
    "Automatic Weapons Handbook Vol 6",
    "Automatic Weapons Handbook Vol 7",
    "Bar Brawling Vol 1",
    "Bar Brawling Vol 2",
    "Bar Brawling Vol 3",
    "Bar Brawling Vol 4",
    "Bar Brawling Vol 5",
    "Bar Brawling Vol 6",
    "Bar Brawling Vol 7",
    "Batter Up Vol 1",
    "Batter Up Vol 2",
    "Batter Up Vol 3",
    "Batter Up Vol 4",
    "Batter Up Vol 5",
    "Batter Up Vol 6",
    "Batter Up Vol 7",
    "Bow Hunters",
    "Crafting Skill Magazine Bundle",
    "Explosive Magazine",
    "Forge Ahead",
    "Handgun Magazine",
    "Home Cooking Weekly",
    "Lucky Looter Vol 1",
    "Lucky Looter Vol 2",
    "Lucky Looter Vol 3",
    "Lucky Looter Vol 4",
    "Lucky Looter Vol 5",
    "Lucky Looter Vol 6",
    "Lucky Looter Vol 7",
    "Magnum Enforcer Vol 1",
    "Magnum Enforcer Vol 2",
    "Magnum Enforcer Vol 3",
    "Magnum Enforcer Vol 4",
    "Magnum Enforcer Vol 5",
    "Magnum Enforcer Vol 6",
    "Magnum Enforcer Vol 7",
    "Medical Journal",
    "Night Stalker Vol 1",
    "Night Stalker Vol 2",
    "Night Stalker Vol 3",
    "Night Stalker Vol 4",
    "Night Stalker Vol 5",
    "Night Stalker Vol 6",
    "Night Stalker Vol 7",
    "Pistol Pete Vol 1",
    "Pistol Pete Vol 2",
    "Pistol Pete Vol 3",
    "Pistol Pete Vol 4",
    "Pistol Pete Vol 5",
    "Pistol Pete Vol 6",
    "Pistol Pete Vol 7",
    "Ranger's Guide to Archery Vol 1",
    "Ranger's Guide to Archery Vol 2",
    "Ranger's Guide to Archery Vol 3",
    "Ranger's Guide to Archery Vol 4",
    "Ranger's Guide to Archery Vol 5",
    "Ranger's Guide to Archery Vol 6",
    "Ranger's Guide to Archery Vol 7",
    "Rifle World",
    "Scrapping 4 Fun",
    "Sharp Sticks",
    "Shotgun Messiah Vol 1",
    "Shotgun Messiah Vol 2",
    "Shotgun Messiah Vol 3",
    "Shotgun Messiah Vol 4",
    "Shotgun Messiah Vol 5",
    "Shotgun Messiah Vol 6",
    "Shotgun Messiah Vol 7",
    "Shotgun Weekly",
    "Sledge Saga Vol 1",
    "Sledge Saga Vol 2",
    "Sledge Saga Vol 3",
    "Sledge Saga Vol 4",
    "Sledge Saga Vol 5",
    "Sledge Saga Vol 6",
    "Sledge Saga Vol 7",
    "Sniper Vol 1",
    "Sniper Vol 2",
    "Sniper Vol 3",
    "Sniper Vol 4",
    "Sniper Vol 5",
    "Sniper Vol 6",
    "Sniper Vol 7",
    "Southern Farming",
    "Spear Hunter Vol 1",
    "Spear Hunter Vol 2",
    "Spear Hunter Vol 3",
    "Spear Hunter Vol 4",
    "Spear Hunter Vol 5",
    "Spear Hunter Vol 6",
    "Spear Hunter Vol 7",
    "Tactical Warfare",
    "Tech Junkie Vol 1",
    "Tech Junkie Vol 2",
    "Tech Junkie Vol 3",
    "Tech Junkie Vol 4",
    "Tech Junkie Vol 5",
    "Tech Junkie Vol 6",
    "Tech Junkie Vol 7",
    "Tech Planet",
    "The Fireman's Almanac Vol 1",
    "The Fireman's Almanac Vol 2",
    "The Fireman's Almanac Vol 3",
    "The Fireman's Almanac Vol 4",
    "The Fireman's Almanac Vol 5",
    "The Fireman's Almanac Vol 6",
    "The Fireman's Almanac Vol 7",
    "The Great Heist Vol 1",
    "The Great Heist Vol 2",
    "The Great Heist Vol 3",
    "The Great Heist Vol 4",
    "The Great Heist Vol 5",
    "The Great Heist Vol 6",
    "The Great Heist Vol 7",
    "The Hunter's Journal Vol 1",
    "The Hunter's Journal Vol 2",
    "The Hunter's Journal Vol 3",
    "The Hunter's Journal Vol 4",
    "The Hunter's Journal Vol 5",
    "The Hunter's Journal Vol 6",
    "The Hunter's Journal Vol 7",
    "Tools Digest",
    "Urban Combat Vol 1",
    "Urban Combat Vol 2",
    "Urban Combat Vol 3",
    "Urban Combat Vol 4",
    "Urban Combat Vol 5",
    "Urban Combat Vol 6",
    "Urban Combat Vol 7",
    "Vehicle Adventures",
    "Wasteland Treasures Vol 1",
    "Wasteland Treasures Vol 2",
    "Wasteland Treasures Vol 3",
    "Wasteland Treasures Vol 4",
    "Wasteland Treasures Vol 5",
    "Wasteland Treasures Vol 6",
    "Wasteland Treasures Vol 7",
    "Wiring 101"
   ]
  },
  {
   "id": "schematics",
   "name": "Schematics",
   "items": [
    "Adv. Muffled Connectors Mod Schematic",
    "Advanced Armor Fittings Mod Schematic",
    "Advanced Armor Plating Mod Schematic",
    "Armor Double Pocket Mod Schematic",
    "Armor Fittings Mod Schematic",
    "Armor Plating Mod Schematic",
    "Armor Pocket Mod Schematic",
    "Armor Quad Pocket Mod Schematic",
    "Armor Triple Pocket Mod Schematic",
    "Arrow Rest Mod Schematic",
    "Bandolier Mod Schematic",
    "Barbed Wire Mod Schematic",
    "Barrel Extender Mod Schematic",
    "Bipod Mod Schematic",
    "Bunker Buster Mod Schematic",
    "Burning Shaft Mod Schematic",
    "Cripple 'Em Mod Schematic",
    "Ergonomic Grip Mod Schematic",
    "Fore Grip Mod Schematic",
    "Fortifying Grip Mod Schematic",
    "Grave Digger Mod Schematic",
    "Helmet Light Mod Schematic",
    "Impact Bracing Mod Schematic",
    "Iron Breaker Mod Schematic",
    "Laser Sight Mod Schematic",
    "Magazine Extender Mod Schematic",
    "Metal Spikes Mod Schematic",
    "Motor Tool Large Tank Mod Schematic",
    "Motor Tool Small Tank Mod Schematic",
    "Muffled Connectors Mod Schematic",
    "Muzzle Brake Mod Schematic",
    "Polymer String Mod Schematic",
    "Rad Remover Mod Schematic",
    "Reflex Sight Mod Schematic",
    "Retracting Stock Mod Schematic",
    "Robotic Drone Armor Plating Mod Schematic",
    "Robotic Drone Cargo Mod Schematic",
    "Robotic Drone Medic Mod Schematic",
    "Robotic Drone Morale Booster Mod Schematic",
    "Robotic Drone Stun Mod Schematic",
    "Robotic Headlamp Mod Schematic",
    "Sawed-off Shotgun Mod Schematic",
    "Scope 2x Mod Schematic",
    "Scope 4x Mod Schematic",
    "Scope 8x Mod Schematic",
    "Serrated Blade Mod Schematic",
    "Shamway Secret Recipe",
    "Shotgun Choke Mod Schematic",
    "Shotgun Duckbill Mod Schematic",
    "Silencer Mod Schematic",
    "Structural Brace Mod Schematic",
    "Super Corn (Seed) Recipe",
    "Tempered Blade Schematic",
    "The Hunter Mod Schematic",
    "Trigger Group: Burst Mod Schematic",
    "Trigger Group: Full Auto Mod Schematic",
    "Trigger Group: Semi Mod Schematic",
    "Vehicle Armor Mod Schematic",
    "Vehicle Expanded Seating Mod Schematic",
    "Vehicle Fuel Saver Mod Schematic",
    "Vehicle Off Road Headlights Mod Schematic",
    "Vehicle Plow Mod Schematic",
    "Vehicle Reserve Fuel Tank Mod Schematic",
    "Vehicle Storage Mod Schematic",
    "Vehicle Super Charger Mod Schematic",
    "Water Purifier Mod Schematic",
    "Weapon Flashlight Mod Schematic",
    "Weighted Head Mod Schematic",
    "Wood Splitter Mod Schematic"
   ]
  },
  {
   "id": "quest",
   "name": "Quest & Treasure",
   "items": [
    "Basic Survival Quest Note",
    "Biome Badge 1",
    "Biome Badge 2",
    "Biome Badge 3",
    "Biome Badge 4",
    "Claude's Treasure Map",
    "Jennifer's Treasure Map",
    "Nickole's Treasure Map",
    "Note from The Duke of Navezgane",
    "Raphael's Treasure Map",
    "Sarah's Treasure Map",
    "Stephan's Treasure Map",
    "Taylor's Treasure Map"
   ]
  },
  {
   "id": "misc",
   "name": "Miscellaneous",
   "items": [
    "Cassadore Supplies",
    "Poop",
    "Snowball",
    "White River Supplies"
   ]
  }
 ]
};
